live_config_reload = true
# window_opacity = 1.0

[colors.bright]
black = "#686868"
blue = "#59C2FF"
cyan = "#95E6CB"
green = "#C2D94C"
magenta = "#FFEE99"
red = "#F07178"
white = "#FFFFFF"
yellow = "#FFB454"

[colors.normal]
black = "#01060E"
blue = "#53BDFA"
cyan = "#90E1C6"
green = "#91B362"
magenta = "#FAE994"
red = "#EA6C73"
white = "#C7C7C7"
yellow = "#F9AF4F"

[colors.primary]
background = "#162229"
foreground = "#9ba8b8"

# [cursor.style]
# blinking = "On"
# shape = "Block"
# unfocused_hollow = false

[env]
TERM = "xterm-256color"

[font]
size = 14

[window]
decorations = "full"
dynamic_title = true
# history = 10000
# multiplier = 3
startup_mode = "Windowed"

[window.dimensions]
columns = 84
lines = 22

[window.padding]
x = 8
y = 8
